[phases.setup]
nixPkgs = ["nodejs-18_x", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "npm run build",
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"