services:
  - type: web
    name: precizu-app
    env: python
    plan: free
    buildCommand: |
      npm ci
      npm run build
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: NODE_VERSION  
        value: 18
    disk:
      name: precizu-disk
      mountPath: /opt/render/project/uploads
      sizeGB: 1