// Estados brasileiros
export const BRAZILIAN_STATES = [
  { code: 'AC', name: 'Acre' },
  { code: 'AL', name: 'Alagoas' },
  { code: 'AP', name: 'Amapá' },
  { code: 'AM', name: 'Amazonas' },
  { code: 'BA', name: 'Bahia' },
  { code: 'CE', name: 'Ceará' },
  { code: 'DF', name: 'Distrito Federal' },
  { code: 'ES', name: 'Espírito Santo' },
  { code: 'GO', name: 'Goiás' },
  { code: 'MA', name: 'Maranhão' },
  { code: 'MT', name: 'Mato Grosso' },
  { code: 'MS', name: 'Mato Grosso do Sul' },
  { code: 'MG', name: 'Minas Gerais' },
  { code: 'PA', name: 'Pará' },
  { code: 'PB', name: 'Paraíba' },
  { code: 'PR', name: 'Paraná' },
  { code: 'PE', name: 'Pernambuco' },
  { code: 'PI', name: 'Piauí' },
  { code: 'RJ', name: 'Rio de Janeiro' },
  { code: 'RN', name: 'Rio Grande do Norte' },
  { code: 'RS', name: 'Rio Grande do Sul' },
  { code: 'RO', name: 'Rondônia' },
  { code: 'RR', name: 'Roraima' },
  { code: 'SC', name: 'Santa Catarina' },
  { code: 'SP', name: 'São Paulo' },
  { code: 'SE', name: 'Sergipe' },
  { code: 'TO', name: 'Tocantins' }
];

// Multiplicadores regionais para cálculo de orçamento
export const REGIONAL_MULTIPLIERS = {
  'AC': 1.3,
  'AL': 1.15,
  'AP': 1.35,
  'AM': 1.35,
  'BA': 1.1,
  'CE': 1.15,
  'DF': 1.05,
  'ES': 1.05,
  'GO': 1.1,
  'MA': 1.2,
  'MT': 1.15,
  'MS': 1.15,
  'MG': 1.05,
  'PA': 1.25,
  'PB': 1.15,
  'PR': 1.0,
  'PE': 1.15,
  'PI': 1.2,
  'RJ': 1.05,
  'RN': 1.15,
  'RS': 1.0,
  'RO': 1.3,
  'RR': 1.4,
  'SC': 1.0,
  'SP': 1.0,
  'SE': 1.15,
  'TO': 1.2
};